version: 0.0
os: linux
files:
  - source:
      - target/plentyentry-application.jar
      - plentyentry-frontend/

    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 60