version: 0.0
os: linux
files:
  - source:
      - target/plentyentry-application.jar
    destination: /tmp/backend/
  - source:
      - plentyentry-frontend/dist
    destination: /tmp/frontend/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 60