version: 0.0
os: linux
files:
    - source:
        - target/plentyentry-application.jar
      destination: /home/ec2-user/target
    - source:
        - scripts/
      destination: /home/ec2-user/scripts
    - source:
        - plentyentry-frontend/dist/plentyentry-frontend/
      destination: /home/ec2-user/frontend/dist/plentyentry-frontend
    - source:
        - appspec.yml
      destination: /home/ec2-user
file_exists_behavior: OVERWRITE
permission:
  - object: /tmpDir
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-frontend.sh
      timeout: 1000
      runas: root
    - location: scripts/start-backend.sh
      timeout: 1000
      runas: root

  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 100