version: 0.0
os: linux
files:
  - source: target/plentyentry-application.jar
    destination: /tmp
hooks:
  -ApplicationStop:
    - scripts: scripts/application-stop.sh
  -ValidationService:
    - scripts: scripts/application-start.sh