version: 0.0
os: linux
files:
  - source:
      - target/plentyentry-application.jar
    destination: /tmpDir
  - source:
      - scripts/
    destination: /tmpDir
  - source:
      - plentyentry-frontend/
    destination: /tmpDir
  - source:
      - plentyentry-frontend/dist/plentyentry-frontend/
    destination: /tmpDir
  - source:
      - appspec.yml
    destination: /tmpDir
file_exists_behavior: RETAIN
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start-backend.sh
    - location: scripts/start-frontend.sh
      timeout: 1000
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 100