version: 0.0
os: linux
files:
  - source: target/plentyentry-application.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 900
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application-start.sh
    - scripts:
      - java -jar /tmp/plentyentry-application.jar
      timeout: 3600