version: 0.0
os: linux
files:
    - source:
        - plentyentry-application.jar
      destination: /
    - source:
        - before-install.sh
      destination: /
    - source:
        - after-install.sh
      destination: /
    - source:
        - start-backend.sh
      destination: /
    - source:
        - validate-service.sh
      destination: /
    - source:
        - appspec.yml
      destination: /
file_exists_behavior: OVERWRITE
permission:
  - object: /tmp
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after-install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start-backend.sh
      timeout: 1000
      runas: root
  ValidateService:
    - location: validate-service.sh
      timeout: 100
