version: 0.0
os: linux
files:
  - source: /
    desitnation: /home/ec2-user/server
file_exists_behavior: OVERWRITE
permission:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: after-install.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: start-backend.sh
      timeout: 1000
      runas: ec2-user
  ValidateService:
    - location: validate-service.sh
      timeout: 300
