version: 0.0
os: linux
files:
  - source: target/plentyentry-application.jar
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
  ApplicationStart:
    - location: scripts/validate-start.sh