version: 0.0
os: linux
files:
  - source:
      - target/plentyentry-application.jar
    destination: /tmpDir
  - source:
      - scripts/
    destination: /tmpDir
  - source:
      - plentyentry-frontend/
    destination: /tmpDir
  - source:
      - plentyentry-frontend/dist/plentyentry-frontend/
    destination: /tmpDir
  - source:
      - appspec.yml
    destination: /tmpDir
permission:
  - object: /tmpDir
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-backend.sh
      timeout: 1000
      runas: ec2-user
    - location: scripts/start-frontend.sh
      timeout: 1000
      runas: ec2-user
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 100
      runas: ec2-user