version: 0.0
os: linux
files:
  - source:
      - target/plentyentry-application.jar
    destination: /tmp/backend/jar/
  - source:
      - scripts/
    destination: /tmp/backend/scripts/
  - source:
      - plentyentry-frontend/
    destination: /tmp/frontend/
  - source:
      - plentyentry-frontend/dist/plentyentry-frontend/
    destination: /tmp/frontend/dist/
  - source:
      - appspec.yml
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start-backend.sh
    - location: scripts/start-frontend.sh
      timeout: 600
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 100