version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - mvn clean -DskipTests
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests
  post_build:
    commands:
      - mvn test
      - java -jar /tmp/plentyentry-application.jar
artifacts:
  files:
    - target/plentyentry-application.jar
    - appspec.yml
    - scripts/before-install.sh
    - scripts/application-start.sh
    - scripts/after-install.sh