version: 0.2
env:
  variables:
    BUILD_ENV: "qa"
    S3_BUCKET: "{{S3_BUCKET}}"
    BUILD_FOLDER: "dist/plentyentry-frontend"
phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: latest
    commands:
      - echo $CODEBUILD_SRC_DIR
      - cd plentyentry-frontend
      - npm install -y npm@latest
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - ls
      - cd ../
  build:
    commands:
      - echo Build started on `date`
      - ls
      - mvn clean install
      - cd plentyentry-frontend
      - ng build --prod --progress
      - cd ../
      - ls -l -F
  post_build:
    commands:
      - echo Tests Started
      - mvn test
artifacts:
  files:
    - target/plentyentry-application.jar
    - appspec.yml
    - scripts/*
    - plentyentry-frontend/dist/plentyentry-frontend/*