version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/plentyentry-application.jar
    - appspec.yml
    - scripts/before-install.sh
    - scripts/application-start.sh
    - scripts/after-install.sh