version: 0.2
env:
  variables:
    BUILD_ENV: "prod"

phases:
  install:
    runtime-versions:
      java: openjdk 17.0.1
      nodejs: 12
    commands:
      - echo $CODEBUILD_SRC_DIR
      - npm install -y npm@latest
      - npm install -g @angular/cli
      - rm package-lock.json
  pre_build:
    commands:
      - mvn clean -DskipTests
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - cd plentyentry-frontend
      - ng build
      - ls -l -F
  post_build:
    commands:
      - echo Tests Started
      - mvn test
artifacts:
  files:
    - target/plentyentry-application.jar
    - appspec.yml
    - scripts/after-install.sh
    - scripts/application-start.sh
    - scripts/before-install.sh
    - scripts/validate-service.sh
    - /plentyentry-frontend/dist/plentyentry-frontend/*