version: 0.2
env:
  variables:
    BUILD_ENV: "prod"

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 12
    commands:
      - echo $CODEBUILD_SRC_DIR
      - mvn clean install
      - cd plentyentry-frontend/
      - npm install -y npm@latest
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - ls
      - cd ../
  build:
    commands:
      - echo Build started on `date`
      - ls
      - mvn clean package
      - cd plentyentry-frontend
      - ng build
      - cd ../
      - ls -l -F
  post_build:
    commands:
      - echo Tests Started
      - mvn test
artifacts:
  files:
    - target/plentyentry-application.jar
    - appspec.yml
    - scripts/after-install.sh
    - scripts/application-start.sh
    - scripts/before-install.sh
    - scripts/validate-service.sh
    - plentyentry-frontend/*