jwt:
  secret: 'kmCZ{4GnBOpX{mb¡NpQ“nzL7pne¶BIjdjCk12sY¶et36ZqgKeiTzN¢Byab6Z6fwgWBA7GWPtP8xssMQNh1bRCuo9F6¢wwT7FALX¶'
pe:
  baseHost: 'http://ec2-3-144-231-140.us-east-2.compute.amazonaws.com:8080/'
server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        synonyms: true
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    password: SabDab2001
    username: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://plentyentry-db.czqacdk2phl7.us-east-2.rds.amazonaws.com:3306/plentyentry

  mail:
    host: localhost
    password: test
    port: 1025
    username: test

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimout: 5000
          timeout: 3000
          writetimeout: 5000
paypal:
  mode: sandbox
  client:
    id: AdDrxG2Q61wNJlHzVSxh6rfcIP7I_mD1YzG51t8tNiHm_odgJz3j6Zt1FtrtQb3zDzBOaALq8SkT9FOH
    secret: EKQm5_ysdbIDZ2CJgQ65kmI95xkLHn6rSzMBl675VtxtDzIuYSf8srSSotKWAX00LtPK_lXdeC-Hrf1C