server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    password:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/plentyentry-db;AUTO_SERVER=TRUE
#Mail Server for local testing
  mail:
    host: localhost
    password: test
    port: 1025
    username: test

    properties:
      mail:
       smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimout: 5000
          timeout: 3000
          writetimeout: 5000
