server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password: SabDab2001
    username: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://plentyentry-db.czqacdk2phl7.us-east-2.rds.amazonaws.com:3306

  mail:
    host: localhost
    password: test
    port: 1025
    username: test

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimout: 5000
          timeout: 3000
          writetimeout: 5000