jwt:
  secret: 'plentyentrycommodus'
pe:
  baseHost: 'http://localhost:80/'
server:
  port: 80
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    password:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/plentyentry-db;AUTO_SERVER=TRUE
#Mail Server for local testing
  mail:
    host: localhost
    password: test
    port: 1025
    username: test

    properties:
      mail:
       smtp:
         ssl:
           trust: "*"
           auth: true
         starttls:
           enable: true
         connectiontimout: 5000
         timeout: 3000
         writetimeout: 5000
paypal:
  mode: sandbox
  client:
    id: AdDrxG2Q61wNJlHzVSxh6rfcIP7I_mD1YzG51t8tNiHm_odgJz3j6Zt1FtrtQb3zDzBOaALq8SkT9FOH
    secret: EKQm5_ysdbIDZ2CJgQ65kmI95xkLHn6rSzMBl675VtxtDzIuYSf8srSSotKWAX00LtPK_lXdeC-Hrf1C
stripe:
  mode: development
  public-key: pk_test_51Kfr2HDAXhrIxCz9JbKqmWo6ZTaUMBUPhY1iukliuy0iRqRoxFVv93oOTnst1mwW2XZMHXqFRLLK3BAmIDCI9CAe00tV99Snt1
  private-key: sk_test_51Kfr2HDAXhrIxCz9mhNotfY56zLN1kLUAMK5dQFAY1Ptgk2rvvkrMu6hIabFKylT1mRcYa8U3osRUjqHz5wWGGOD00dvbwtdrV
amazonProperties:
  endpointUrl: https://eventimagesbucket.s3-us-east-2.amazonaws.com
  accessKey: AKIAU3CJ5DRKN27DX2N3
  secretKey: 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
  bucketName: eventimagesbucket
  smtpUsername: AKIAU3CJ5DRKDH5E27UE
  smtpPassword: BNsPvdqU5zcTYG378bm9q8hRPpSOXWD31StHYq5gHjov
  mailHost: email-smtp.us-east-2.amazonaws.com
  accessKeyMail: AKIAU3CJ5DRKIFX7E4IG
  secretKeyMail: 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